-- V1：租户表（PRD §9 t_tenant；FR-TEN-01/03）
-- 行级隔离单档（SHARED_TABLE）：isolation_mode 预置默认值，多档切换不做（FR-TEN-03）；
-- name 唯一：对应 FR-TEN-01「重复名称 409」；tenantId 一经创建不可改（由应用层约束）。
CREATE TABLE t_tenant (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           VARCHAR(128) NOT NULL,
    isolation_mode VARCHAR(32)  NOT NULL DEFAULT 'SHARED_TABLE',
    status         VARCHAR(32)  NOT NULL DEFAULT 'ACTIVE',
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uk_t_tenant_name UNIQUE (name)
);

COMMENT ON TABLE t_tenant IS '租户（FR-TEN-01：id 一经创建不可改、name 唯一）';
