-- V2：M1 数据层（PRD §9）——知识库 / 文档 / 切片 / 向量 + 事务性发件箱 + 摄入账本 + 对账/计量
-- 说明：
--   * 行级隔离单档：所有业务表带 tenant_id（BIGINT，对应 t_tenant.id）
--   * t_ingest_ledger 的 (doc_id, version) 即 FR-ING-01 的幂等键（唯一约束仲裁）
--   * t_outbox_event 与业务写入同事务（事务性发件箱），发布由 OutboxRelay 轮询完成（ADR-005）

CREATE EXTENSION IF NOT EXISTS vector;

-- 知识库（FR-KB-01；权限维度之一，org_id 预留组织维度）
CREATE TABLE t_knowledge_base (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id  BIGINT       NOT NULL,
    org_id     BIGINT,
    name       VARCHAR(128) NOT NULL,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uk_t_kb_tenant_name UNIQUE (tenant_id, name)
);

-- 文档（FR-KB-02/03/04；content 为演示替身：不做 OCR/文件存储深水区，PRD §10）
-- version 支撑切片版本化（FR-ING-03）：同名重传 version +1，旧版本切片在新版本索引完成后失效
CREATE TABLE t_document (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id  BIGINT       NOT NULL,
    kb_id      BIGINT       NOT NULL,
    name       VARCHAR(256) NOT NULL,
    content    TEXT         NOT NULL,
    version    INT          NOT NULL DEFAULT 1,
    status     VARCHAR(32)  NOT NULL DEFAULT 'PENDING',  -- PENDING/INDEXED/DELETED/FAILED（FR-KB-04）
    deleted_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uk_t_document_kb_name UNIQUE (kb_id, name)
);

CREATE INDEX idx_t_document_tenant ON t_document (tenant_id);

-- 切片（meta 含 ACL 字段供 filter 下推，PRD §9）
CREATE TABLE t_chunk (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id  BIGINT      NOT NULL,
    doc_id     BIGINT      NOT NULL,
    version    INT         NOT NULL,
    seq        INT         NOT NULL,
    content    TEXT        NOT NULL,
    meta       JSONB       NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_t_chunk_doc_version_seq UNIQUE (doc_id, version, seq)
);

-- 向量（pgvector；meta 与 t_chunk.meta 一致，保证可见集 filter 可下推）
CREATE TABLE t_vector (
    chunk_id  BIGINT PRIMARY KEY,
    embedding vector(1536) NOT NULL,
    meta      JSONB NOT NULL DEFAULT '{}'::jsonb
);

CREATE INDEX idx_t_vector_embedding_hnsw ON t_vector USING hnsw (embedding vector_cosine_ops);

-- 事务性发件箱（FR-KB-02/03：与业务写入同事务；PENDING → SENT，重试耗尽 → FAILED）
CREATE TABLE t_outbox_event (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id    BIGINT       NOT NULL,
    aggregate_id BIGINT       NOT NULL,
    type         VARCHAR(128) NOT NULL,   -- 事件类型即 Kafka topic 名（ADR-005 约定）
    payload      JSONB        NOT NULL,
    status       VARCHAR(16)  NOT NULL DEFAULT 'PENDING',  -- PENDING/SENT/FAILED
    retry_count  INT          NOT NULL DEFAULT 0,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    sent_at      TIMESTAMPTZ
);

CREATE INDEX idx_t_outbox_status_created ON t_outbox_event (status, created_at);

-- 摄入账本：幂等键唯一约束 + 摄入状态机 + 对账数据源（FR-ING-01/06）
-- 状态机：PROCESSING（抢占中）→ INDEXED / DELETED / FAILED（FAILED 可被重试重新抢占）
CREATE TABLE t_ingest_ledger (
    doc_id     BIGINT      NOT NULL,
    version    INT         NOT NULL,
    tenant_id  BIGINT      NOT NULL,
    status     VARCHAR(16) NOT NULL,       -- PROCESSING/INDEXED/DELETED/FAILED
    node       VARCHAR(64),
    error      TEXT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (doc_id, version)
);

-- 对账报告（FR-ING-06 / FR-COST-05）
CREATE TABLE t_reconcile_report (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type           VARCHAR(32) NOT NULL,   -- CONSISTENCY / BILLING
    window_start   TIMESTAMPTZ NOT NULL,
    window_end     TIMESTAMPTZ NOT NULL,
    mismatch_count INT         NOT NULL DEFAULT 0,
    detail_ref     TEXT,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- LLM/工具调用计量明细（P4a 四维归因；单表 + 租户/时间索引，PRD §5.6）
CREATE TABLE t_llm_call_log (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id         BIGINT      NOT NULL,
    session_id        VARCHAR(64),
    step_no           INT,
    tool              VARCHAR(64),
    model             VARCHAR(64),
    prompt_tokens     INT         NOT NULL DEFAULT 0,
    completion_tokens INT         NOT NULL DEFAULT 0,
    latency_ms        INT,
    cost              NUMERIC(12, 6),
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_t_llm_call_log_tenant_time ON t_llm_call_log (tenant_id, created_at);
