-- V4：可见集 ACL 载体与审计留痕（ADR-008 落实；PRD FR-PERM-01 / FR-PERM-05）
-- 说明：
--   * kbACL / docACL 用「表 + effect」而非业务表枚举列：需表达「对特定用户的跨组织例外授权（ALLOW）」
--     与「对特定用户屏蔽（DENY）」，枚举做不到；两张表同构，一张形态两处用。
--   * 审计不可变：应用层只 INSERT，数据库触发器再拒 UPDATE/DELETE——「不可变留痕」具备代码级证据。

-- 知识库级 ACL 例外（ADR-008 决策 2：org 门之外的显式授权 / 拒绝）
CREATE TABLE t_kb_acl (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id  BIGINT      NOT NULL,
    kb_id      BIGINT      NOT NULL,
    user_id    BIGINT      NOT NULL,
    effect     VARCHAR(8)  NOT NULL,   -- ALLOW（跨组织例外授权）/ DENY（显式拒绝）
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_t_kb_acl  UNIQUE (kb_id, user_id),
    CONSTRAINT ck_t_kb_acl_effect CHECK (effect IN ('ALLOW', 'DENY'))
);

-- 可见集算法按「用户」检索其 ACL 条目
CREATE INDEX idx_t_kb_acl_user ON t_kb_acl (tenant_id, user_id);

-- 文档级 ACL 例外（单独授权某文档 / 屏蔽敏感文档）
CREATE TABLE t_doc_acl (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id  BIGINT      NOT NULL,
    doc_id     BIGINT      NOT NULL,
    user_id    BIGINT      NOT NULL,
    effect     VARCHAR(8)  NOT NULL,   -- ALLOW / DENY
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_t_doc_acl UNIQUE (doc_id, user_id),
    CONSTRAINT ck_t_doc_acl_effect CHECK (effect IN ('ALLOW', 'DENY'))
);

CREATE INDEX idx_t_doc_acl_user ON t_doc_acl (tenant_id, user_id);

-- 审计留痕（FR-PERM-05；「谁在何时对哪个目标做了什么」，越权尝试同样留痕）
CREATE TABLE t_audit_log (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id  BIGINT       NOT NULL,
    actor      VARCHAR(64)  NOT NULL,   -- 主体标识（M2：userId；接入认证后为认证主体）
    action     VARCHAR(64)  NOT NULL,   -- RETRIEVAL_DENIED / TOOL_DENIED / QUOTA_EXCEEDED ...
    target     VARCHAR(128),            -- 目标对象（kbId / docId / 工具名）
    result     VARCHAR(16)  NOT NULL,   -- DENIED / ALLOWED ...
    detail     TEXT,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX idx_t_audit_log_tenant_time ON t_audit_log (tenant_id, created_at);

-- 不可变保护：只允许 INSERT（应用层没有 UPDATE/DELETE 路径，数据库层再钉一次）
CREATE FUNCTION t_audit_log_reject_mutation() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 't_audit_log 为不可变审计日志：拒绝 % 操作（FR-PERM-05）', TG_OP;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_t_audit_log_immutable
    BEFORE UPDATE OR DELETE ON t_audit_log
    FOR EACH ROW EXECUTE FUNCTION t_audit_log_reject_mutation();
