-- V5：工具副作用治理（ADR-009）；PRD FR-TOOL-01~04 / FR-PERM-03
-- 说明：
--   * t_tool_invocation：幂等键唯一约束 + 重放仲裁状态机（ADR-009 决策 2）；
--   * t_ticket：演示替身（PRD §10：不做退款；工单零资金风险），idem_key 唯一是「双重幂等」的最终防线；
--   * t_compensation_log：失败触发的补偿计划与执行日志（UNIQUE(invocation_id) 保证计划幂等）。

-- 演示工单（零资金风险替身；同一来源单号在任何会话/重放下都只建一张单）
CREATE TABLE t_ticket (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id  BIGINT       NOT NULL,
    idem_key   VARCHAR(128) NOT NULL,   -- 业务键（来源单号）
    title      VARCHAR(256) NOT NULL,
    assignee   VARCHAR(64),
    status     VARCHAR(16)  NOT NULL DEFAULT 'OPEN',   -- OPEN/CANCELLED
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uk_t_ticket_tenant_idem UNIQUE (tenant_id, idem_key)
);

-- 工具调用账本（幂等键仲裁；SUCCEEDED/FAILED 为终态，重放返回首见终态）
CREATE TABLE t_tool_invocation (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id  BIGINT       NOT NULL,
    idem_key   VARCHAR(160) NOT NULL,
    session_id VARCHAR(64)  NOT NULL,
    step_no    INT          NOT NULL,
    tool       VARCHAR(64)  NOT NULL,
    input      TEXT         NOT NULL,   -- 输入快照（幂等指纹、补偿与审计的上下文）
    result     TEXT,                    -- 首次结果（SUCCEEDED 后重放复用）
    error      TEXT,                    -- 首见失败原因（FAILED 后重放复用）
    status     VARCHAR(16)  NOT NULL,   -- PROCESSING/SUCCEEDED/FAILED
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uk_t_tool_invocation_idem UNIQUE (tenant_id, idem_key)
);

CREATE INDEX idx_t_tool_invocation_session ON t_tool_invocation (tenant_id, session_id, id);

-- 补偿计划与日志（失败时生成 PENDING；执行器按 invocation_id DESC 逆序执行）
CREATE TABLE t_compensation_log (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id     BIGINT      NOT NULL,
    invocation_id BIGINT      NOT NULL,   -- 被补偿的成功调用
    action        VARCHAR(72) NOT NULL,   -- UNDO:<tool>
    status        VARCHAR(16) NOT NULL,   -- PENDING/SUCCEEDED/FAILED
    attempt       INT         NOT NULL DEFAULT 0,
    detail        TEXT,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_t_compensation_invocation UNIQUE (invocation_id)
);

CREATE INDEX idx_t_compensation_status ON t_compensation_log (tenant_id, status);
