-- V6：租户预算（P4a 配额强一致；ADR-010 决策 7）
-- 说明：未配置 = 不启用配额检查（演示默认零门槛）；period 为账期（YYYY-MM）。
CREATE TABLE t_budget (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id      BIGINT       NOT NULL,
    period         VARCHAR(16)  NOT NULL,   -- 账期 YYYY-MM
    token_limit    BIGINT       NOT NULL,   -- token 当量上限（演示期为「操作当量」口径，ADR-010 决策 8）
    cost_limit     NUMERIC(12,6),
    degrade_policy VARCHAR(32),             -- P4b 预留（M3 可选）
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uk_t_budget_tenant_period UNIQUE (tenant_id, period)
);
